src/Entity/AdminUser.php
<?php

namespace Kisphp\SecurityBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Kisphp\Entity\KisphpEntityInterface;
use Kisphp\Entity\ToggleableInterface;
use Kisphp\Utils\Status;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\MappedSuperclass()
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\Entity
 * @ORM\Table(name="admin_users", options={"collate": "utf8_general_ci", "charset": "utf8"})
 * @ORM\HasLifecycleCallbacks()
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"adminuser": "AppBundle\Entity\AdminUser"})
 */
abstract class AdminUser implements UserInterface, KisphpEntityInterface, ToggleableInterface
{
    /**
     * @ORM\Column(type="integer", options={"unsigned": true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", options={"default": Kisphp\Utils\Status::ACTIVE})
     */
    protected $status = Status::ACTIVE;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $registered;

    /**
     * @var string
     * @ORM\Column(type="string", length=64)
     */
    protected $name;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, unique=true)
     */
    protected $email;

    /**
     * @var string
     * @ORM\Column(type="string", length=32)
     */
    protected $roles = 'ROLE_ADMIN';

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    protected $password;

    /**
     * @var ArrayCollection
     */
    protected $password_form;

    /**
     * @var ArrayCollection
     */
    protected $account_form;

    public function __construct()
    {
        $this->password_form = new ArrayCollection();
        $this->account_form = new ArrayCollection();
    }

    /**
     * @return array
     */
    public function __sleep()
    {
        return ['id', 'email'];
    }

    /**
     * @ORM\PrePersist()
     */
    public function updateModifiedDatetime()
    {
        if ($this->getRegistered() === null) {
            $this->setRegistered(new \DateTime());
        }
    }

    /**
     * @return string
     */
    public function getFullname()
    {
        return $this->getName();
    }

    /**
     * @param array $roles
     */
    public function setRoles(array $roles)
    {
        $this->roles = implode(',', $roles);
    }

    /**
     * @return array
     */
    public function getRoles()
    {
        $roles = $this->roles;
        if (is_string($roles) && !empty($this->roles)) {
            $roles = explode(',', $this->roles);
        }

        if (empty($roles)) {
            $roles = ['ROLE_ADMIN'];
        }

        return $roles;
    }

    /**
     * @return null|string|void
     */
    public function getSalt()
    {
    }

    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * @param string $username
     */
    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return \DateTime
     */
    public function getRegistered()
    {
        return $this->registered;
    }

    /**
     * @param \DateTime $registered
     */
    public function setRegistered($registered)
    {
        $this->registered = $registered;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * @return ArrayCollection
     */
    public function getPasswordForm()
    {
        return $this->password_form;
    }

    /**
     * @param ArrayCollection $password_form
     */
    public function setPasswordForm($password_form)
    {
        $this->password_form = $password_form;
    }

    /**
     * @return ArrayCollection
     */
    public function getAccountForm()
    {
        return $this->account_form;
    }

    /**
     * @param ArrayCollection $account_form
     */
    public function setAccountForm($account_form)
    {
        $this->account_form = $account_form;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }
}

src/Controller/AdminUserController.php
<?php

namespace Kisphp\SecurityBundle\Controller;

use Kisphp\FrameworkAdminBundle\Controller\AbstractController;
use Kisphp\SecurityBundle\Form\User\AdminUserCreateForm;
use Kisphp\SecurityBundle\Form\User\AdminUserEditForm;
use Kisphp\SecurityBundle\Form\User\UserPasswordForm;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Template()
 */
class AdminUserController extends AbstractController
{
    const SECTION_TITLE = 'section.title.admin_user';
    const MODEL_NAME = 'model.admin_user';
    const LISTING_TEMPLATE = '@KisphpSecurity/AdminUser/index.html.twig';

    /**
     * @var array
     */
    protected $section = [
        self::EDIT_PATH => 'adm_admin_user_edit',
        self::LIST_PATH => 'adm_admin_user',
        self::ADD_PATH => 'adm_admin_user_add',
        self::STATUS_PATH => 'adm_admin_user_status',
        self::DELETE_PATH => 'adm_admin_user_delete',
    ];

    /**
     * @param Request $request
     * @param int $id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, $id = 0)
    {
        $currentUser = $this->getUser();
        $entity = $this->get(static::MODEL_NAME)->find($id);

        if ($id > 0 && !$entity) {
            $this->addFlash('error', 'User does not exists!');
            return $this->redirect(
                $this->generateUrl('adm_admin_user_edit', ['id' => $currentUser->getId()])
            );
        }

        if (in_array('ROLE_SUPER_ADMIN', $currentUser->getRoles()) === false && $currentUser->getId() !== $entity->getId()) {
            $this->addFlash('error', 'You do not have permissions to edit other user!');
            return $this->redirect(
                $this->generateUrl('adm_admin_user_edit', ['id' => $currentUser->getId()])
            );
        }

        $form = $this->createEditForm($request, $id);
        /** @var \Kisphp\FrameworkAdminBundle\Entity\AdminUser $entity */
        $formPass = $this->createForm(UserPasswordForm::class, null, [
            'current_user' => $this->getUser(),
            'admin_roles' => $this->getParameter('admin_roles'),
        ]);
        $formPass->handleRequest($request);

        if ($formPass->isSubmitted() && $formPass->isValid()) {
            /** @var \Kisphp\FrameworkAdminBundle\Entity\AdminUser $data */
            $data = $formPass->getData();
            $providedPassword = $data->getPassword();

            $password = $this->get('security.password_encoder')
                ->encodePassword($entity, $providedPassword)
            ;

            $entity->setPassword($password);

            $this->get(static::MODEL_NAME)->save($entity);

            return $this->redirectAfterSave($entity, 'Password was successfully saved');
        }

        if ($form->isSubmitted() && $form->isValid()) {
            return $this->processSubmittedForm($form);
        }

        return $this->render(
            '@KisphpSecurity/AdminUser/edit.html.twig',
            [
                'id' => $id,
                'entity' => $entity,
                'form' => $form->createView(),
                'form_pass' => $formPass->createView(),
                'attached' => $this->getAttachedFiles($id),
                'section' => $this->section,
                'html_editor' => static::HTML_EDITOR_ENABLED,
                'upload_type' => static::UPLOAD_TYPE,
                'images_list_url' => $this->getImagesEditUrl($id),
                'section_title' => static::SECTION_TITLE . (($id > 0) ? '.edit' : '.create'),
            ]
        );
    }

    /**
     * @param Request $request
     * @param $object
     *
     * @return \Symfony\Component\Form\FormInterface
     */
    protected function createFormObject(Request $request, $object)
    {
        $currentUser = $this->getUser();

        $formOptions = [
            'current_user' => $currentUser,
            'admin_roles' => $this->getParameter('admin_roles'),
        ];

        if ($object->getId() > 0) {
            $form = $this->createForm(AdminUserEditForm::class, $object, $formOptions);
            $form->handleRequest($request);

            return $form;
        }

        $form = $this->createForm(AdminUserCreateForm::class, $object, $formOptions);
        $form->handleRequest($request);

        return $form;
    }

    /**
     * @param Form $form
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function processSubmittedForm(Form $form)
    {
        $entity = $form->getData();

        if ($entity->getId() === null) {
            $password = $this->get('security.password_encoder')
                ->encodePassword($entity, $entity->getPassword())
            ;
            $entity->setPassword($password);
        }

        $savedEntity = $this->saveObjectEntity($entity);

        return $this->redirectAfterSave($savedEntity);
    }
}

src/Resources/views/AdminUser/edit.html.twig
{% extends 'FrameworkAdminBundle::layout.html.twig' %}

{% block box_header %}
    <a href="{{ path(section.list_path) }}" class="btn btn-xs btn-github"><i class="fa fa-list"></i> {{ 'btn.list' | trans }}</a>
    {% if section.add_path != '' %}
        <a href="{{ path(section.add_path) }}" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> {{ 'btn.create' | trans }}</a>
    {% endif %}
{% endblock %}

{% block body %}

    {% block body_form %}
        {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

        <div class="box-body2">
            {{ form_widget(form) }}
        </div>

        <div class="box-footer">
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <input type="submit" class="btn btn-success" value="{{ 'btn.save' | trans }}">
                </div>
            </div>
        </div>
        {{ form_end(form) }}
    {% endblock %}

    {% block body_upload %}
        {% if id > 0 and upload_type != '' %}
            {% include '@FrameworkAdmin/components/upload-images.html.twig' with { type: upload_type } %}
        {% endif %}
    {% endblock %}

{% endblock %}

{% block body_box %}
    {{ parent() }}

    {% if id > 0 %}
    <div class="box">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <h3 class="box-title">Change Password</h3>
                </div>
            </div>
        </div>
        <div class="box-body">
            {{ form_start(form_pass, {'attr': {'class': 'form-horizontal'}}) }}

            <div class="box-body2">
                {{ form_widget(form_pass) }}
            </div>

            <div class="box-footer">
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2">
                        <input type="submit" class="btn btn-success" value="{{ 'btn.save' | trans }}">
                    </div>
                </div>
            </div>
            {{ form_end(form_pass) }}
        </div>
    </div>
    {% endif %}

{% endblock %}

{% block js %}
    {{ parent() }}
    {% if html_editor is defined and html_editor %}
        {% include 'FrameworkAdminBundle:components:_html-editor.html.twig' %}
    {% endif %}
    {% if id is defined and id > 0 and upload_type is defined and upload_type != '' %}
        {% include '@FrameworkAdmin/components/upload-images-js.html.twig' %}
    {% endif %}
{% endblock %}

src/Resources/views/AdminUser/index.html.twig
{% extends '@FrameworkAdmin/components/listing.html.twig' %}

{% import '@FrameworkAdmin/macros/navigation-macros.html.twig' as navBtn %}
{% import '@FrameworkAdmin/macros/table-btn-macros.html.twig' as tbl %}

{% block box_header %}
    {{ navBtn.list(path(section.list_path), 'btn.list') }}
    {{ navBtn.create(path(section.add_path), 'btn.create') }}
{% endblock %}

{% block listing_table_content %}

    <thead>
    <tr>
        <th width="200">{{ 'table.header.options' | trans }}</th>
        <th>{{ 'table.header.id' | trans }}</th>
        <th>{{ 'table.header.fullname' | trans }}</th>
        <th>{{ 'table.header.email' | trans }}</th>
        <th>{{ 'table.header.status' | trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% for item in items %}
        <tr id="row-{{ item.id }}">
            <td>
                {{ tbl.edit(path(section.edit_path, {id: item.id})) }}
                {{ tbl.delete(item.id, path(section.delete_path)) }}
            </td>
            <td>{{ item.id }}</td>
            <td><a href="{{ path(section.edit_path, {id: item.id}) }}">{{ item.fullname }}</a></td>
            <td>{{ item.email }}</td>
            {% if app.user is not null %}
            {{ statusToggle(item, path(section.status_path), (app.user.id > item.id)) }}
            {% else %}
            <td>&nbpsp;</td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}